# примеры API-запросов

@baseUrl = http://localhost:8000/api

GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token ef1f85361c5415d9c8590b385205f2775253b8d9

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/5/
Content-Type: application/json
Authorization: Token ef1f85361c5415d9c8590b385205f2775253b8d9

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-10-01
Content-Type: application/json



###

# удаление объявления
DELETE {{baseUrl}}/advertisements/4/
Authorization: Token 1eb140e940050503586dd0b9c2e63818c626d911
