# примеры API-запросов

@baseUrl = http://localhost:8000/api

GET {{baseUrl}}/advertisements/favorites/
Content-Type: application/json
Authorization: Token 1eb140e940050503586dd0b9c2e63818c626d911



###

GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 1eb140e940050503586dd0b9c2e63818c626d911


###


#POST /api/v1/advertisements/{pk}/add_to_favorites/: для добавления объявления в избранное;
#POST /api/v1/advertisements/{pk}/remove_from_favorites/: для удаления объявления из избранного.

# создание объявления
POST {{baseUrl}}/advertisements/38/add_to_favorites/
Authorization: Token 1eb140e940050503586dd0b9c2e63818c626d911

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/5/
Content-Type: application/json
Authorization: Token ef1f85361c5415d9c8590b385205f2775253b8d9

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-10-01
Content-Type: application/json



###

# удаление объявления
DELETE {{baseUrl}}/advertisements/8/
Authorization: Token 1eb140e940050503586dd0b9c2e63818c626d911
