# Generated by Django 4.1.7 on 2023-05-08 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0003_favoriteadvertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteadvertisement',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement'),
        ),
        migrations.AlterField(
            model_name='favoriteadvertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
