# Generated by Django 4.1.7 on 2023-05-08 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0005_alter_favoriteadvertisement_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteadvertisement',
            unique_together={('user', 'advertisement')},
        ),
    ]
