# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP893",
  "description": "Датчик в комнате"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "name": "242",
  "description": "Перенес датчик 4 в комнату"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 4,
  "temperature": -105.36
}

###

# получение информации по датчику
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
