# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Помидорка9",
  "description": "Лучшая помидорка на рынке"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Самые n сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/5/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=помидор
Content-Type: application/json



###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "адрес не дом и не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 7,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 6,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/3/
Content-Type: application/json

{
  "positions": [
    {
      "product": 7,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 6,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json



###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks?ordering=id
Content-Type: application/json